# Generated by Django 5.1.3 on 2024-11-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(help_text='City or Area', max_length=255)),
                ('incident_type', models.CharField(choices=[('harassment', 'Harassment'), ('domestic_violence', 'Domestic Violence'), ('workplace_discrimination', 'Workplace Discrimination'), ('other', 'Other')], default='other', max_length=50)),
                ('incident_date', models.DateField(help_text='Date of Incident')),
                ('complaint', models.TextField(help_text='Describe the incident in detail')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
