# Generated by Django 5.1.3 on 2024-11-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('feedback', models.TextField(help_text='Provide your feedback')),
                ('rating', models.CharField(choices=[('average', 'Average'), ('good', 'Good'), ('poor', 'Poor')], default='good', max_length=10)),
                ('suggestion', models.TextField(blank=True, help_text='Any suggestions?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
